dist: trusty
sudo: required
language: python
python:
  - "3.6"
script:
- python -m nltk.downloader vader_lexicon stopwords wordnet brown_tei gutenberg punkt popular
- pip install -e .
- pytest -v 
before_install:
  - sudo apt-get install -y enchant 
  - pip install pytest-sugar
addons:
  apt:
    update: true
