dist: trusty
sudo: required
language: python
python:
  - "3.6"
script:
- pytest -v --cov=nlpfunctions
- pip install -e .
before_install:
  - sudo apt-get install -y enchant 
addons:
  apt:
    update: true
